# Generated by Django 4.0.3 on 2022-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=120)),
                ('downloads', models.IntegerField()),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
